variable "project" {}
variable "vm_name" {}
variable "machine_type" {}
variable "region" {}
variable "zone" {}
variable "network" {}
variable "subnet" {}
variable "cidr_range" {}
variable "ip_name" {}
variable "service_account_name" {}
variable "domain" {}